### ISSUE TITLE
SP-API getPackageTrackingDetails does not respond correctly when an unknown event code is responded.

### ISSUE THREAD

**Issue by Tetsuya-Takiguchi** [amazon-php/sp-api-sdk#191]
Hi, I am currently developing an application using this library.
Thank you very much.

Now, when we run getPackageTrackingDetails from this library, if an unknown event code is responded by Amazon, it will result in an exception.

## log
```
Type: InvalidArgumentException

Message: Invalid value for enum '\AmazonPHP\SellingPartner\Model\FulfillmentOutbound\EventCode', must be one of: 'EVENT_101', 'EVENT_102', 'EVENT_201', 'EVENT_202', 'EVENT_203', 'EVENT_204', 'EVENT_205', 'EVENT_206', 'EVENT_301', 'EVENT_302', 'EVENT_304', 'EVENT_306', 'EVENT_307', 'EVENT_308', 'EVENT_309', 'EVENT_401', 'EVENT_402', 'EVENT_403', 'EVENT_404', 'EVENT_405', 'EVENT_406', 'EVENT_407', 'EVENT_408', 'EVENT_409', 'EVENT_411', 'EVENT_412', 'EVENT_413', 'EVENT_414', 'EVENT_415', 'EVENT_416', 'EVENT_417', 'EVENT_418', 'EVENT_419'

Filename: /var/www/html/app/ebisu/application/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php

Line Number: 348
```

The event codes we detected are the following event codes (we asked Amazon what the event codes mean).

1. EVENT_438 : Customer has requested delivery appointment to be rescheduled. Delivery may be delayed due to the customer request.
2. EVENT_444 : Customer has requested the package to be forwarded to a different address. The request will be processed shortly.

Also, Amazon has informed us that event codes will continue to be added or changed due to changes in the delivery system.
Therefore, we would appreciate it if the library could return the value as it is even if an unknown event code is responded to.
Is it possible to request a correction?

**Comment by norberttech** [comment]
Eh Amazon... So as you already know, the problem comes from incomplete model definitions in [models](https://github.com/amzn/selling-partner-api-models). 
Could you please open an issue in [models](https://github.com/amzn/selling-partner-api-models) repository (so I can track progress)? 

In the meantime, I'm disabling enum value validation which should solve your problem for now. 

Please let me know if changes from https://github.com/amazon-php/sp-api-sdk/pull/192 works for you so I can tag next stable release.
