### ISSUE TITLE
TypeError when serializing ItemSearchResults when no pages or refinements are present

### ISSUE THREAD

**Issue by sw-Oldeu** [amazon-php/sp-api-sdk#242]
Version: 4.0.8
What causes the error: After calling the `CatalogItems::searchCatalogItems()` method call `ItemSearchResults::jsonSerialize()`. The method `ItemSearchResults::jsonSerialize()` expects an Object of type `Pagination` but instead `null` is returned.

I think just make the response optional would save the problem. But I don't know what impact this change may have and which ResponseResults may have the same error.

Regards

**Comment by owsiakl** [comment]
Hey @sw-Oldeu. You're right, looks like the pagination is returned only when there will be more than 10 items in the response. According to the Amazons documentation it should always be present, but we have multiple cases in many different endpoints with a similar problem.
Anyway, this is fixed in version 5 - those fields are now optional.
Thanks!
