### ISSUE TITLE
Feature request: add vendor apis

### ISSUE THREAD

**Issue by underdpt** [amazon-php/sp-api-sdk#72]
Hello,

I've been tinkering with this library and it feels great, thanks!

My question... Do you have any plans to add vendor apis?

https://github.com/amzn/selling-partner-api-models/tree/main/models:

- vendor-direct-fulfillment-inventory-api-model
- vendor-direct-fulfillment-orders-api-model
- vendor-direct-fulfillment-payments-api-model
- vendor-direct-fulfillment-shipping-api-model 
- vendor-direct-fulfillment-transactions-api-model
- vendor-invoices-api-model
- vendor-orders-api-model
- vendor-shipments-api-model
- vendor-transaction-status-api-model

I would like to help with this, but I'm totally lost with client api generators. Maybe you could give some guidelines and I can try to add it.

**Comment by norberttech** [comment]
hey @underdpt 
Vendors API is on our roadmap, it's just hard to find time to work on it. 

Basically, all models are automatically generated from the repository you pointed out. 

## How to launch code generation
In order to launch models generation, you need to execute composer, [generate](https://github.com/amazon-php/sp-api-sdk/blob/1.x/composer.json#L44) by executing in console `composer generate`. Just be sure to have docker up and running on your machine. 

However, before you generate anything you need to first make sure that proper definitions are in place. 

### 1) Configuration

Configuration for all of SDK's is kept here: https://github.com/amazon-php/sp-api-sdk/tree/1.x/config (its pretty much copy-paste with some small names adjustments).

### 2) generate.sh 

https://github.com/amazon-php/sp-api-sdk/blob/1.x/bin/generate.sh this is where you need to put docker command that would generate models you need. 

### 3) Renaming generated SDK's 

The last step is to make sure that SDK names are unified, for that you might need to use this [renaming script](https://github.com/amazon-php/sp-api-sdk/blob/1.x/bin/rename.php) because those that came from generation are usually misleading or bad looking. 

Also please make sure to launch `generate` command from PHP 7.4, at least this is the version I'm using. 



I hope that will help you in case you would like to add those vendors API SDK's, if not I will definitely take care of that somewhere later this year.

**Comment by underdpt** [comment]
Thanks for your explanation. I'm sorry I don't have docker and i'm currently unable to put any effort on it now :-(

**Comment by norberttech** [comment]
vendor api skd's are now available
